erDiagram
    persona {
        INT id_persona PK
        TEXT nombre "NN"
        TEXT apellido "NN"
        TEXT dni "NN"
        TEXT hashedPassword "NN"
        TEXT email "NN"
        TEXT telefono "NN"
        TEXT direccion "NN"
        TIMESTAMP fecha_registro "NN"
    }

    cliente {
        INT id_cliente PK
        INT id_persona FK "NN"
        INT categoria
        TEXT estado "NN"
    }

    empleado {
        INT id_empleado PK
        INT id_persona FK "NN"
        TEXT legajo "NN"
        TEXT cargo "NN"
        TEXT departamento "NN"
        TIMESTAMP fecha_ingreso "NN"
        REAL salario "NN"
        TEXT sucursal "NN"
    }

    cuenta {
        INT id_cuenta PK
        TEXT nro_cuenta "NN"
        INT id_cliente FK "NN"
        INT id_tipo_cuenta FK "NN"
        REAL saldo "NN"
        REAL tasa_interes
        TIMESTAMP fecha_creacion "NN"
    }

    tipo_cuenta {
        INT id_tipo_cuenta PK
        TEXT nombre "NN"
        TEXT descripcion
    }

    transaccion {
        INT id_transaccion PK
        INT id_cuenta FK "NN"
        INT id_tipo_transaccion FK "NN"
        REAL monto "NN"
        TIMESTAMP fecha "NN"
    }

    tipo_transaccion {
        INT id_tipo_transaccion PK
        TEXT nombre "NN"
        TEXT descripcion
    }

    persona ||--|| cliente : "id_persona referencia id_persona"
    persona ||--|| empleado : "id_persona referencia id_persona"
    cliente ||--o{ cuenta : "id_cliente referencia id_cliente"
    tipo_cuenta ||--o{ cuenta : "id_tipo_cuenta referencia id_tipo_cuenta"
    cuenta ||--o{ transaccion : "id_cuenta referencia id_cuenta"
    tipo_transaccion ||--o{ transaccion : "id_tipo_transaccion referencia id_tipo_transaccion"
